# Generated by Django 5.1 on 2025-10-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("original_content", models.TextField()),
                ("plain_text", models.TextField()),
                ("source_url", models.URLField(max_length=1000, unique=True)),
                ("publication_date", models.CharField(max_length=19)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-scraped_at"],
            },
        ),
    ]
